version: '3'
services:
  db:
    image: postgres:9.6
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/
    ports: 
      - 80:80

  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports: 
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8888

volumes:
  dados: